version: '3.8'
services:
  app-backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PERENUAL_API_KEY=${PERENUAL_API_KEY} # reference the api key from the .env file
    depends_on:
      - mongodb

  app-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - app-backend

  mongodb:
    image: mongo
    container_name: plantscript-mongo
    volumes:
      - plantscript-mongodbdata:/data/db
    ports:
      - "27017:27017"

volumes:
  plantscript-mongodbdata:
