import Joi from 'joi';

const plantSchema = Joi.object({
  id: Joi.number().required(),
  common_name: Joi.string().required(),
  scientific_name: Joi.array().items(Joi.string()).required(),
  other_names: Joi.array().items(Joi.string()).allow(null).optional(),
  cycle: Joi.string().required(),
  watering: Joi.string().required(),
  sunlight: Joi.array().items(Joi.string()).required(),
  family: Joi.string().allow(null).optional(),
  origin: Joi.array().items(Joi.string()).allow(null).optional(),
  type: Joi.string().allow('', 'Coming Soon', null).default(null).optional(),
  dimension: Joi.string().allow('', 'Coming Soon', null).default(null).optional(),
  dimensions: Joi.object({
    type: Joi.string().required(),
    min_value: Joi.number().required(),
    max_value: Joi.number().required(),
    unit: Joi.string().required(),
  }).allow(null).optional(),
  attracts: Joi.array().items(Joi.string()).allow(null).optional(),
  propagation: Joi.array().items(Joi.string()).allow(null).optional(),
  hardiness: Joi.object({
    min: Joi.string().required(),
    max: Joi.string().required(),
  }).allow(null).optional(),
  depth_water_requirement: Joi.array().items(Joi.string()).allow(null).optional(),
  volume_water_requirement: Joi.array().items(Joi.string()).allow(null).optional(),
  watering_period: Joi.string().allow('', 'Coming Soon', null, null).default(null).optional(),
  watering_general_benchmark: Joi.object({
    value: Joi.string().required(),
    unit: Joi.string().required(),
  }).allow(null).optional(),
  plant_anatomy: Joi.array().items(Joi.string()).allow(null).optional(),
  pruning_month: Joi.array().items(Joi.string()).allow(null).optional(),
  pruning_count: Joi.array().items(Joi.number()).allow(null).optional(),
  seeds: Joi.number().allow(null).optional(),
  maintenance: Joi.string().allow('', 'Coming Soon', null).default(null).optional(),
  soil: Joi.array().items(Joi.string()).allow(null).optional(),
  growth_rate: Joi.string().allow('', 'Coming Soon', null).default(null).optional(),
  drought_tolerant: Joi.boolean().optional(),
  salt_tolerant: Joi.boolean().optional(),
  thorny: Joi.boolean().optional(),
  invasive: Joi.boolean().optional(),
  tropical: Joi.boolean().optional(),
  indoor: Joi.boolean().optional(),
  care_level: Joi.string().allow('', 'Coming Soon', null).default(null).optional(),
  pest_susceptibility: Joi.array().items(Joi.string()).allow(null).optional(),
  pest_susceptibility_api: Joi.string().allow('Coming Soon', null, '').default(null).optional(),
  flowers: Joi.boolean().optional(),
  flowering_season: Joi.string().allow('', 'Coming Soon', null).default(null).optional(),
  flower_color: Joi.string().allow('', 'Coming Soon', null).default(null).optional(),
  cones: Joi.boolean().optional(),
  fruits: Joi.boolean().optional(),
  edible_fruit: Joi.boolean().optional(),
  edible_fruit_taste_profile: Joi.string().allow('', 'Coming Soon', null).default(null).optional(),
  fruit_nutritional_value: Joi.string().allow('', 'Coming Soon', null).default(null).optional(),
  fruit_color: Joi.array().items(Joi.string()).allow(null).optional(),
  harvest_season: Joi.string().allow('', 'Coming Soon', null).default(null).optional(),
  leaf: Joi.boolean().optional(),
  leaf_color: Joi.array().items(Joi.string()).allow(null).optional(),
  edible_leaf: Joi.boolean().optional(),
  cuisine: Joi.boolean().optional(),
  medicinal: Joi.boolean().optional(),
  poisonous_to_humans: Joi.number().optional(),
  poisonous_to_pets: Joi.number().optional(),
  description: Joi.string().allow('', 'Coming Soon', null).default(null).optional(),
  default_image: Joi.object({
    license: Joi.number().required(),
    license_name: Joi.string().required(),
    license_url: Joi.string().uri().required(),
    original_url: Joi.string().uri().required(),
    regular_url: Joi.string().uri().required(),
    medium_url: Joi.string().uri().required(),
    small_url: Joi.string().uri().required(),
    thumbnail: Joi.string().uri().required(),
  }).allow(null).optional(),
  other_images: Joi.any().optional(), // needs api provider supreme sub
}).unknown(true); // allow other fields without validation

export default plantSchema;
