import Joi from 'joi';

// Assuming PlantDetails includes complex objects and arrays, like dimensions, hardiness, etc.
const plantSchema = Joi.object({
  id: Joi.number().required(),
  common_name: Joi.string().required(),
  scientific_name: Joi.array().items(Joi.string()).required(),
  other_names: Joi.array().items(Joi.string()).optional(),
  cycle: Joi.string().required(),
  watering: Joi.string().required(),
  sunlight: Joi.array().items(Joi.string()).required(),
  family: Joi.string().allow(null).optional(),
  origin: Joi.array().items(Joi.string()).optional(),
  type: Joi.string().optional(),
  dimension: Joi.string().optional(),
  dimensions: Joi.object({
    type: Joi.string().required(),
    min_value: Joi.number().required(),
    max_value: Joi.number().required(),
    unit: Joi.string().required(),
  }).optional(),
  attracts: Joi.array().items(Joi.string()).optional(),
  propagation: Joi.array().items(Joi.string()).optional(),
  hardiness: Joi.object({
    min: Joi.string().required(),
    max: Joi.string().required(),
  }).optional(),
  depth_water_requirement: Joi.array().items(Joi.string()).optional(),
  volume_water_requirement: Joi.array().items(Joi.string()).optional(),
  watering_period: Joi.string().allow(null).optional(),
  watering_general_benchmark: Joi.object({
    value: Joi.string().required(),
    unit: Joi.string().required(),
  }).optional(),
  plant_anatomy: Joi.array().items(Joi.string()).optional(),
  pruning_month: Joi.array().items(Joi.string()).optional(),
  pruning_count: Joi.array().items(Joi.number()).optional(),
  seeds: Joi.number().optional(),
  maintenance: Joi.string().allow(null).optional(),
  soil: Joi.array().items(Joi.string()).optional(),
  growth_rate: Joi.string().optional(),
  drought_tolerant: Joi.boolean().optional(),
  salt_tolerant: Joi.boolean().optional(),
  thorny: Joi.boolean().optional(),
  invasive: Joi.boolean().optional(),
  tropical: Joi.boolean().optional(),
  indoor: Joi.boolean().optional(),
  care_level: Joi.string().optional(),
  pest_susceptibility: Joi.array().items(Joi.string()).optional(),
  pest_susceptibility_api: Joi.string().optional(),
  flowers: Joi.boolean().optional(),
  flowering_season: Joi.string().allow(null).optional(),
  flower_color: Joi.string().optional(),
  cones: Joi.boolean().optional(),
  fruits: Joi.boolean().optional(),
  edible_fruit: Joi.boolean().optional(),
  edible_fruit_taste_profile: Joi.string().optional(),
  fruit_nutritional_value: Joi.string().optional(),
  fruit_color: Joi.array().items(Joi.string()).optional(),
  harvest_season: Joi.string().allow(null).optional(),
  leaf: Joi.boolean().optional(),
  leaf_color: Joi.array().items(Joi.string()).optional(),
  edible_leaf: Joi.boolean().optional(),
  cuisine: Joi.boolean().optional(),
  medicinal: Joi.boolean().optional(),
  poisonous_to_humans: Joi.number().optional(),
  poisonous_to_pets: Joi.number().optional(),
  description: Joi.string().optional(),
  // Include default_image and other_images if needed, following a similar pattern
  default_image: Joi.object({
    license: Joi.number().required(),
    license_name: Joi.string().required(),
    license_url: Joi.string().uri().required(),
    original_url: Joi.string().uri().required(),
    regular_url: Joi.string().uri().required(),
    medium_url: Joi.string().uri().required(),
    small_url: Joi.string().uri().required(),
    thumbnail: Joi.string().uri().required(),
  }).optional(),
  // Assuming other_images is an array of URLs
  other_images: Joi.array().items(Joi.string().uri()).optional(),
});

export default plantSchema;
