import { PlantDetails } from '../models/plantInterfaces';

export const mockPlantDetails: PlantDetails = {
    _id: "60f8e9f3b4b6c7d3e6a3d3a0",
    id: 1,
    common_name: "Mock Plant",
    scientific_name: ["Mockus plantae"],
    other_name: ["Test Plant"],
    family: "Mockaceae",
    origin: ["Testland"],
    type: "Herb",
    dimension: "Medium",
    dimensions: {
        type: "Height",
        min_value: 10,
        max_value: 20,
        unit: "cm",
    },
    cycle: "Perennial",
    attracts: ["Bees"],
    propagation: ["Cuttings", "Seeds"],
    hardiness: {
        min: "-5",
        max: "30",
    },
    hardiness_location: {
        full_url: "https://example.com/hardiness_zone_map",
        full_iframe: "<iframe src='https://example.com/hardiness_zone_map'></iframe>",
    },
    watering: "Moderate",
    depth_water_requirement: ["15cm"],
    volume_water_requirement: ["1L per week"],
    watering_period: "Weekly",
    watering_general_benchmark: {
        value: "1",
        unit: "L/week",
    },
    plant_anatomy: ["Roots", "Stem", "Leaves"],
    sunlight: ["Partial shade"],
    pruning_month: ["March", "September"],
    pruning_count: ["Once"],
    seeds: 100,
    maintenance: "Low",
    care_guides: "Regular watering and monthly fertilization.",
    soil: ["Loamy"],
    growth_rate: "Medium",
    drought_tolerant: false,
    salt_tolerant: false,
    thorny: false,
    invasive: false,
    tropical: true,
    indoor: true,
    care_level: "Easy",
    pest_susceptibility: ["Aphids"],
    pest_susceptibility_api: "https://example.com/pests/aphids",
    flowers: true,
    flowering_season: "Spring",
    flower_color: "Yellow",
    cones: false,
    fruits: true,
    edible_fruit: true,
    edible_fruit_taste_profile: "Sweet",
    fruit_nutritional_value: "High in Vitamin C",
    fruit_color: ["Red"],
    harvest_season: "Autumn",
    leaf: true,
    leaf_color: ["Green", "Yellow"],
    edible_leaf: false,
    cuisine: true,
    medicinal: true,
    poisonous_to_humans: 0,
    poisonous_to_pets: 0,
    description: "A mock plant used for testing purposes.",
    default_image: {
        license: 1,
        license_name: "Creative Commons",
        license_url: "https://creativecommons.org/licenses/by-sa/4.0/",
        original_url: "https://example.com/mock_plant.jpg",
        regular_url: "https://example.com/mock_plant_regular.jpg",
        medium_url: "https://example.com/mock_plant_medium.jpg",
        small_url: "https://example.com/mock_plant_small.jpg",
        thumbnail: "https://example.com/mock_plant_thumbnail.jpg",
    },
    other_images: "https://example.com/mock_plant_other.jpg"
};
